- name: Install Helm
  hosts: all
  become: yes
  tasks:
    - name: Updates
      apt:
        update_cache: yes

    - name: download helm key
      get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/keyrings/helm.asc

    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: Helm's APT repo
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}\n
 signed-by=/etc/apt/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
        update_cache: yes

    - name: Install helm
      apt:
        name: helm
        state: present
