- name: jellyfin
  hosts: jellyfin
  become: yes
  gather_facts: false
  tasks:
    - name: Updates
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install packages and extrepo
      apt:
        pkg:
          - sudo
          - python3
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - curl
          - nfs-common #nfs mounting
          - extrepo #jellyfin

    - name: Create a new user
      user:
        name: jellybox
        state: present
        shell: /bin/bash
        home: /home/jellybox
        groups: sudo
        comment: "user jellybox created by Ansible"

    - name: Enable extrepo
      shell: sudo extrepo enable jellyfin 

    - name: Updates
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        pkg:
          - jellyfin