---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp
  namespace: exponentify
  labels:
    app: exp
spec:
  selector:
    matchLabels:
      app: exp
  replicas: 1
  template:
    metadata:
      labels:
        app: exp
    spec:
      containers:
      - name: exp
        image: ghcr.io/alisxx/exp:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghregcred
---
apiVersion: v1
kind: Service
metadata:
  name: exp
  namespace: exponentify
spec:
  selector:
    app: exp
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
#  tls:
#  - secretName: tls-secret
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: exp
              port:
                number: 8088
