apiVersion: v1
kind: PersistentVolume
metadata:
  name: iregistry-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /mnt/zfs/iregistry
