apiVersion: v1
kind: PersistentVolume
metadata:
  name: iregistry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: docker-registry-storage
  hostPath:
    path: /mnt/zfs/iregistry
